/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DeLetterBase } from "./DeLetterBase";
export * as factories from "./factories";
export { DeLetterBase__factory } from "./factories/DeLetterBase__factory";
